stages:
  - build

build:
  image: ubuntu
  stage: build
  before_script:
    - sudo apt update && sudo apt install emacs
    - make install
    - touch empty.el
  script:
    - fg42 --script empty.el
