stages:
  - build

build:
  image: ubuntu
  stage: build
  before_script:
    - apt update && apt install -y make wget sudo git emacs
    - make install
    - touch empty.el
  script:
    - fg42 --script empty.el
