stages:
  - build

build:
  image: debian:stable-slim
  stage: build
  before_script:
    - apt update && apt install -y make wget git emacs
    - git clone https://gitlab.com/FG42/FG42 ~/.fg42/ && cd ~/.fg42/ && make install && touch empty.el
  script:
    - fg42 -nw --script empty.el && echo "Done"
