#! /bin/sh

export FG42_HOME="$(cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P)"

FG42_WM=false emacs --name FG42 \
              --no-site-file --no-site-lisp --no-splash --title FG42 \
              -L $FG42_HOME/core \
              -L $FG42_HOME/extensions \
              -l $FG42_HOME/core/fg42.el \
              -l ~/.v3.el "$@"
